profiles:
  cloud_qwen:
    api_key_env: OPENROUTER_KEY
    base_url: https://openrouter.ai/api/v1
    model: qwen/qwen-plus
    params:
      seed: 123
      temperature: 0.5
      top_p: 0.9
  local_qwen:
    api_key_env: LM_STUDIO_KEY
    base_url: http://localhost:1234/v1
    model: qwen2.5-7b
    params:
      seed: 42
      temperature: 0.4
      top_p: 0.9
  saödlkjö:
    api_key_env: frfew
    base_url: wrqf
    model: sdlöav#dsfa
    params:
      seed: 42
      temperature: 3.0
      top_p: 0.9
